"""empty message

Revision ID: 56df95287374
Revises: 7e2e5493cfbe
Create Date: 2022-03-16 14:36:58.848708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56df95287374'
down_revision = '7e2e5493cfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenseTable', 'expenseName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incomeTable', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incomeTable', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomeTable', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incomeTable', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenseTable', 'expenseName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
