"""empty message

Revision ID: 57c8cca59d4b
Revises: 
Create Date: 2022-03-13 14:31:10.615467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c8cca59d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenseTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expenseName', sa.String(), nullable=False),
    sa.Column('vrNo', sa.Integer(), nullable=True),
    sa.Column('expenseDate', sa.String(), nullable=False),
    sa.Column('expenseReason', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.Column('entryAdded', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenseTable_id'), 'expenseTable', ['id'], unique=False)
    op.create_table('incomeTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flatNo', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.Column('entryAdded', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomeTable_id'), 'incomeTable', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomeTable_id'), table_name='incomeTable')
    op.drop_table('incomeTable')
    op.drop_index(op.f('ix_expenseTable_id'), table_name='expenseTable')
    op.drop_table('expenseTable')
    # ### end Alembic commands ###
