"""empty message

Revision ID: 598bbdfa634f
Revises: 56df95287374
Create Date: 2022-03-17 13:54:26.607560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598bbdfa634f'
down_revision = '56df95287374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
