"""empty message

Revision ID: 6854b433349e
Revises: 598bbdfa634f
Create Date: 2022-03-17 14:00:18.132784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6854b433349e'
down_revision = '598bbdfa634f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomeTable', 'flatNo',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomeTable', 'flatNo',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
