"""empty message

Revision ID: 7bce7a104d0a
Revises: 57c8cca59d4b
Create Date: 2022-03-13 19:56:02.358017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bce7a104d0a'
down_revision = '57c8cca59d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomeTable', sa.Column('date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomeTable', 'date')
    # ### end Alembic commands ###
