"""empty message

Revision ID: 7e2e5493cfbe
Revises: af111711840d
Create Date: 2022-03-15 11:08:04.122129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2e5493cfbe'
down_revision = 'af111711840d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenseTable', sa.Column('expenseAmount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenseTable', 'expenseAmount')
    # ### end Alembic commands ###
