"""empty message

Revision ID: af111711840d
Revises: ae82fade8e5d
Create Date: 2022-03-14 12:37:51.808539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af111711840d'
down_revision = 'ae82fade8e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carryforward',
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.Column('cf', sa.Integer(), nullable=False),
    sa.Column('nextMonthCF', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('createdAt')
    )
    op.create_index(op.f('ix_carryforward_createdAt'), 'carryforward', ['createdAt'], unique=False)
    op.alter_column('incomeTable', 'flatNo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomeTable', 'flatNo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_carryforward_createdAt'), table_name='carryforward')
    op.drop_table('carryforward')
    # ### end Alembic commands ###
